### ISSUE TITLE
Quebrar capítulos em mais arquivos

### ISSUE THREAD

**Issue by gutosurrex** [livro-aberto/ensino_medio#11]
Olá a todos, acho que realmente seria muito bom termos um capítulo quebrado em aproximadamente uns quatro arquivos. Por exemplo vetores no plano está muito maior do que fica confortável na plataforma...

Como vocês acham que poderia ser uma divisão que faça sentido acadêmico?

**Comment by gutosurrex** [comment]
Adorei a idéia, vou tentar implementar uma interface melhor pra lidar com arquivos.

**Comment by hjbortol** [comment]
Fabio e Augusto, acho que deveríamos viabilizar um sistema que permitisse comentários atividade por atividade, como na plataforma antiga. Fui tentar fazer um comentário de uma atividade que está lá em cima. Isto é muito ruim.

**Comment by simas0** [comment]
Desmembrei o arquivo de Geometria em diversos arquivos e isso melhorou um pouco. Veja o que acham.
