### ISSUE TITLE
Modificações de Layout para acomodar o formato de roteiro

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/ensino_medio#38]
Caros (não consegui incluir Letícia e Cydara e demais nessa discussão, pois não estão registrados nesse ramo ensino_medio do GitHub),

(1) No roteiro há a indicação do tempo de aula necessário. Em "Vetores", isto está dentro do box "Habilidades". Acho que este item bem como a "Fase de elaboração" poderiam estar em boxes próprios.

(2) No roteiro há a lista de objetivos gerais e específicos (inclusive, com códigos). Pensamos que em cada atividade deveria haver o exercício mental e a indicação por escrito de quais destes objetivos/habilidades estão sendo contempladas. Este tipo de registro permitirá fazer uma estatística para ver se eles estão contemplados e balanceados.

Um abraço, Dirce e Humberto.

**Comment by simas0** [comment]
(1) Hoje o roteiro contém os campos: número de aulas necessárias, fase de elaboração, habilidade, etc. Na verdade roteiro é um documento que contém o planejamento do capítulo. Sugestões de alteração pode ser feitas, mas acho que não é o caso, certo? Para mais detalhes sobre o roteiro veja o link https://www.umlivroaberto.com/BookCloud/Metodologia/master/view/roteiro.html

**Comment by hjbortol** [comment]
@simas, com relação a (1), deixe-me explicar melhor: não é mudar o roteiro mas, sim, adequar o layout (divisão dos boxes) do texto para refletir o que foi decidido para o roteiro. Por exemplo, na figura a seguir, a sugestão de tempo necessário e a fase de elaboração estão escritos dentro do bloco "Habilidades". Não deveria ser, não é?

![image](https://user-images.githubusercontent.com/7694624/29211114-7f8a3faa-7e6d-11e7-8eb7-da1f23ced317.png)

**Comment by hjbortol** [comment]
Com a ajuda do Fábio, os boxes estão corretos e refletindo o que está estabelecido no roteiro.

**Comment by gutosurrex** [comment]
Acho que essas informações deveriam ser mais bem catalogadas. Podemos fazer uma mudança da sintaxe do sphinx para incluir algo como:

```
.. habilidade::
   :aulas: 4
   :bncc: AF101

   Nessa habilidade...
```

Isso permitiria uma compilação de estatísticas como disse o Humberto. Mas isso tem que ser requerido como um issue da BookCloud a ser feito mais para o futuro.

**Comment by simas0** [comment]
Eu ainda acho que o roteiro deveria ser uma caixa única com Campus a serem preenchidos como um formulário.

_Sent from my Lenovo K33b36 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hjbortol** [comment]
Hummm ... Pode ser, mas as caixas deixam bem visíveis onde se começa um campo e onde ele termina.

**Comment by gutosurrex** [comment]
Podemos ter os dois mundos. O roteiro pode ser parecido com um formulário e exibido com diversas caixas. Mas aí eu teria que entender melhor como fazer isso no sphinx.
