### ISSUE TITLE
(1) Quem irá fazer os diagramas? (2) Compatibilidade da fonte do texto e do diagrama

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/ensino_medio#41]
Caros,

(1) Como está a questão sobre a responsabilidade da confecção dos diagramas? É obrigação de cada equipe elaborar os diagramas já na sua versão final para o livro ou ainda vale fazer uma versão mais ou menos rapidamente para depois alguém providenciar uma versão definitiva de melhor qualidade?

(2) Aqui vem uma questão de editoração: é importante garantir mecanismos na plataforma que compatibilize as fontes usadas no texto e nos diagramas. No Piloto de Frações, por exemplo, existem figuras que usam uma fonte e no texto, outra:

![image](https://user-images.githubusercontent.com/7694624/29176521-6eb977f0-7dc2-11e7-9749-ecd6ef26431f.png)

**Comment by simas0** [comment]
Figuras apropriadas são fundamentais para o aprendizado do estudante. As figuras devem ser feitas pelas equipes elaboração em versão não definitiva, pode ser um desenho a mão, por exemplo. Mas deve haver um cuidado grande em se expressar na figura os aspectos que espera-se abordar. Não são aceitas meras descrições em frases das figuras, um esboço é fundamental.

As figuras serão refeitas de modo que a fonte seja a mesma da utilizada no texto.

As figuras devem ser indicadas se são figuras artísticas (figuras com personagens, fotos, etc) e figuras matemáticas (gráficos, figuras geométricas, etc).

**Comment by hjbortol** [comment]
Beleza! Obrigado!
