### ISSUE TITLE
Algumas padronizações

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/ensino_medio#59]
Caros,

Acho que precisamos criar algum mecanismo (uma página?) para padronizar e registrar a formatação de alguns termos. Por exemplo:

(1) Depois de ":" letra sempre minúscula ou maiúscula?
(2) "Ensino Médio" ou "ensino médio"? "Escola Básica" ou "escola básica"?
(3) Matemática (substantivo) com letra maiúscula.
(4)  Ao falar com professor, vamos usar "caro Professor" ou "caro professor"?
(5) GeoGebra (e não Geogebra).

Bem, por enquanto, criei este documento Google Docs colaborativo onde estou registrando o que vai aparecendo ...

https://docs.google.com/document/d/1KxsmCc73jg3WAgVM4IpFRR91Oo0a7XI_jFrWeYKLbQ4/edit?usp=sharing

**Comment by simas0** [comment]
Caros, criei o arquivo abaixo para isso na plataforma. Encontra-se em Metodologia. Sugiro que todos coloquem lá os padrões que julgarem adequados, caso alguém queira modificar alguma coisa, inicie uma discussão na plataforma.

https://www.umlivroaberto.com/BookCloud/Metodologia/master/view/linguagem-do-livro.html
