### ISSUE TITLE
Compra de livros

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/ensino_medio#71]
@simas0, aquela proposta para compra de livros vai convergir? Gostaria de comprar este livro aqui ...

@Lhaylla  ...

https://www.amazon.com/Moon-Illusion-Maurice-Hershenson-ebook/dp/B00CWD1BH4/ref=mt_kindle?_encoding=UTF8&me=

![image](https://user-images.githubusercontent.com/7694624/35646639-ed71d128-06b6-11e8-93e4-5dbadfca09ce.png)

**Comment by simas0** [comment]
Caro XP, boa noite! Poderia comprar o livro que o Humberto está querendo,
por favor? Cordialmente, Simas

2018-01-31 19:14 GMT-02:00 hjbortol <notifications@github.com>:
