### ISSUE TITLE
Função quadrática

### ISSUE THREAD

**Issue by simas0** [livro-aberto/ensino_medio#73]
Seguem algumas correções que gostaria que fossem efetuadas antes do envio do capítulo à revisão.

1. O Praticando é uma seção de atividades, não o título de uma atividade. Alterei isso no texto no primeiro Praticando.
2. Faltou o Para o professor desta atividade.
3. Para saber mais é uma seção, não um box, veja [Metodologia](https://www.umlivroaberto.org/BookCloud/Metodologia/master/view/Design.html)
4. As seções Organizando, Praticando e Explorando são com o código
```

**************
Explorando
**************

```

Estou corrigindo algumas coisas direto no texto. Seria bom vocês darem uma olhada depois.

**Comment by simas0** [comment]
1. Os rótulos são em letras minúsculas
```
.. _sub-org-i-4-transformacoes:
```
2. Alguns Explorando são seguidos por Praticando, mas deveriam ser seguidos por Organizando as ideias (veja metodologia),
3. Praticando é seção e não box.
![image](https://user-images.githubusercontent.com/16407253/36939067-d9ede072-1f09-11e8-9091-3b99e31fb867.png)
4. Movi as referências bibliográficas para o início do capítulo. Elas parecem estar desordenadas. Deveriam estar em ordem alfabética.

**Comment by AM0RIM** [comment]
Essas mudanças que você está implementando são no master ou em algum ramo em particular?Para continuar efetivando essas mudanças que você iniciou, precisarei abrir um outro ramo?

De Amorim, Luiz.

 

    Em sábado, 3 de março de 2018 18:18:43 BRT, Fabio Simas <notifications@github.com> escreveu:  
 
 Os rótulos são em letras minúsculas.. _sub-org-i-4-transformacoes:
   
   - Alguns Explorando são seguidos por Praticando, mas deveriam ser seguidos por Organizando as ideias (veja metodologia),
   - Praticando é seção e não box.   

   - Movi as referências bibliográficas para o início do capítulo. Elas parecem estar desordenadas. Deveriam estar em ordem alfabética.
