### ISSUE TITLE
ramos

### ISSUE THREAD

**Issue by AM0RIM** [livro-aberto/ensino_medio#76]
Na 3a criei um ramo do Master para acertar a bibliografia. Dei COMMIT e, agora, que iria fazer outras alterações que foram pedidas, esse ramo sumiu e todos os ramos que eu tenho estão desatualizados em relação ao master. Seria bom que, ao entrar em um ramo, que ele exibisse uma notificação de atualização em relação ao Master, para ser aceito ou não, e em um novo ramo ou sobre o atual.

**Comment by simas0** [comment]
Oi Amorim, os seus ramos estão desatualizados em relação ao Master porque você não deve ter feito commit neles. Quando fizer, ele estará sempre atualizado em relação ao Master. Exceto os ramos dos capítulos são permanentes, embora não seja necessário também. Todos os demais somem 2 dias após a revisão do ramo superior, no caso o Master.

Se você quer um ramo atualizado com o Master, sem submeter as alterações do outro ramo, você pode criar outro ramo.

**Atenção:** Manter ramos sem realizar o commit pode gerar perda de informação. No caso de outra pessoa, em outro ramo, atualizar o mesmo trecho do texto que você depois de você.

**Comment by gutosurrex** [comment]
Eu acho que temos que mudar algumas coisas sobre como funcionam os commits e submissões. Mas antes temos que conversar um pouco.
