### ISSUE TITLE
Pushs automaticos

### ISSUE THREAD

**Issue by gutosurrex** [livro-aberto/ensino_medio#8]
Eu coloquei o livro nesse repositório agora.

Dessa forma podemos por exemplo visualizar versões antigas, ver todos os commits... Mas por enquanto, não mudem nada direto no git!

**Comment by simas0** [comment]
Excelente iniciativa, @gutosurrex !!! 

Agora temos uma nova ferramenta para a elaboração! Você pode visualizar versões antigas dos arquivos da nossa coleção. Para isso você precisa clicar em `<>Code` (ao lado de `Issues`, nesta janela) e depois no nome do arquivo que você quer ver a história. em seguida procure o botão `History` para ver todos os commits feitos para este arquivo. Experimente!
